#!/bin/sh -e

umask 0000

APP_ID=org.webosinternals.navit
OLD_DATADIR=/media/internal/.app-storage/file_.media.cryptofs.apps.usr.palm.applications.org.webosinternals.navit_0
APP_DIR=/media/cryptofs/apps/usr/palm/applications/$APP_ID
NAVIT_USER_DATADIR=/media/internal/appdata/$APP_ID
CERT_STORE=/etc/ssl/certs/appsigning-bundle.crt
CRT=$APP_DIR/package-sig.crt

mkdir -p $NAVIT_USER_DATADIR/maps

# Migrate data from old to new directories
if [ -d $OLD_DATADIR ]
then
	mv $OLD_DATADIR/* $NAVIT_USER_DATADIR
	rmdir $OLD_DATADIR
	# Replace espeak with speech-dispatcher in navit.xml
	sed -i -re "/org.webosinternals.espeak/ s/<speech type=\"cmdline\".*\/>/<speech type=\"speech_dispatcher\" data=\"100\" cps=\"15\" \/>/" $NAVIT_USER_DATADIR/navit.xml
fi

if [ -d /media/internal/MapsNavit ]
then
	mv /media/internal/MapsNavit/* $NAVIT_USER_DATADIR/maps
	rmdir /media/internal/MapsNavit
	# Change map-directory in navit.xml
	sed -i -re "s/\/media\/internal\/MapsNavit/\$NAVIT_USER_DATADIR\/maps/" $NAVIT_USER_DATADIR/navit.xml
fi

(cd $APP_DIR/dist_files/; find) | while read l
do
	s="$APP_DIR/dist_files/${l}"
	d="$NAVIT_USER_DATADIR/${l}"

	if [ -d "${s}" ]
 	then
		test ! -d "${d}" && mkdir -p "${d}"
	else
		if [ ! -f "${d}.md5sum" ]
		then
			md5sum "${d}" > "${d}.md5sum"
		fi

		if md5sum -c "${d}.md5sum"
		then
			mv "${d}" "${d}.old"
			cp "${s}" "${d}"
			md5sum "${d}" > "${d}.md5sum"
		else
			cp "${s}" "${d}.new"
		fi
	fi
done

# Make jailer trust our jail_app.conf
SUBJECT=$(openssl x509 -in $CRT -text | grep " \+Subject:" | sed -re 's/.*Subject//' -e 's/[:,] /\//g')
if ! grep -q "subject= $SUBJECT" $CERT_STORE
then
	(echo "subject= $SUBJECT"
	 echo "================================================"
	 cat $CRT
	) >> $CERT_STORE
fi
